// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2J-fImlWi-08H2I6RNDgDTy6WP2rMn4k',
    appId: '1:292555539494:web:0a5cedd171f1d4cd5052e7',
    messagingSenderId: '292555539494',
    projectId: 'fsm-app-92d6f',
    authDomain: 'fsm-app-92d6f.firebaseapp.com',
    storageBucket: 'fsm-app-92d6f.appspot.com',
    measurementId: 'G-R7RM1WNBDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkm6BJnt2c8NE9uBIU42sRGq-2p1WQDD8',
    appId: '1:292555539494:android:55347e9a875d05755052e7',
    messagingSenderId: '292555539494',
    projectId: 'fsm-app-92d6f',
    storageBucket: 'fsm-app-92d6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4vxx1hGTwa57vB4aqk93fDu6eWlSZ-LU',
    appId: '1:292555539494:ios:e139c64fdeea612b5052e7',
    messagingSenderId: '292555539494',
    projectId: 'fsm-app-92d6f',
    storageBucket: 'fsm-app-92d6f.appspot.com',
    iosBundleId: 'com.example.fsmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4vxx1hGTwa57vB4aqk93fDu6eWlSZ-LU',
    appId: '1:292555539494:ios:e139c64fdeea612b5052e7',
    messagingSenderId: '292555539494',
    projectId: 'fsm-app-92d6f',
    storageBucket: 'fsm-app-92d6f.appspot.com',
    iosBundleId: 'com.example.fsmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2J-fImlWi-08H2I6RNDgDTy6WP2rMn4k',
    appId: '1:292555539494:web:b55810c11c1813525052e7',
    messagingSenderId: '292555539494',
    projectId: 'fsm-app-92d6f',
    authDomain: 'fsm-app-92d6f.firebaseapp.com',
    storageBucket: 'fsm-app-92d6f.appspot.com',
    measurementId: 'G-MM0C62BS2Q',
  );
}
